In [1]:
import pandas as pd

orders = pd.read_csv('../OneDrive/Desktop/GA_Capstone_Datasets/olist_orders_dataset.csv')
items = pd.read_csv('../OneDrive/Desktop/GA_Capstone_Datasets/olist_order_items_dataset.csv')
payments = pd.read_csv('../OneDrive/Desktop/GA_Capstone_Datasets/olist_order_payments_dataset.csv')
customers = pd.read_csv('../OneDrive/Desktop/GA_Capstone_Datasets/olist_customers_dataset.csv')
locations = pd.read_csv('../OneDrive/Desktop/GA_Capstone_Datasets/olist_geolocation_dataset.csv')
products = pd.read_csv('../OneDrive/Desktop/GA_Capstone_Datasets/olist_products_dataset.csv')
translation = pd.read_csv('../OneDrive/Desktop/GA_Capstone_Datasets/product_category_name_translation.csv')
reviews = pd.read_csv('../OneDrive/Desktop/GA_Capstone_Datasets/olist_order_reviews_dataset.csv')

In [2]:
# Adding the new rows
translation.loc[len(translation)] = ['portateis_cozinha_e_preparadores_de_alimentos', 'kitchen_laptops_and_food_preparators']  # Add the first word and translation
translation.loc[len(translation)] = ['pc_gamer', 'pc_gamer']        # Add the second word and translation

pd.set_option('display.max_row', None)

translation

,product_category_name,product_category_name_english
0,beleza_saude,health_beauty
1,informatica_acessorios,computers_accessories
2,automotivo,auto
3,cama_mesa_banho,bed_bath_table
4,moveis_decoracao,furniture_decor
5,esporte_lazer,sports_leisure
6,perfumaria,perfumery
7,utilidades_domesticas,housewares
8,telefonia,telephony
9,relogios_presentes,watches_gifts
10,alimentos_bebidas,food_drink
11,bebes,baby
12,papelaria,stationery
13,tablets_impressao_imagem,tablets_printing_image
14,brinquedos,toys
15,telefonia_fixa,fixed_telephony
16,ferramentas_jardim,garden_tools
17,fashion_bolsas_e_acessorios,fashion_bags_accessories
18,eletroportateis,small_appliances
19,consoles_games,consoles_games
20,audio,audio
21,fashion_calcados,fashion_shoes
22,cool_stuff,cool_stuff
23,malas_acessorios,luggage_accessories
24,climatizacao,air_conditioning
25,construcao_ferramentas_construcao,construction_tools_construction
26,moveis_cozinha_area_de_servico_jantar_e_jardim,kitchen_dining_laundry_garden_furniture
27,construcao_ferramentas_jardim,costruction_tools_garden
28,fashion_roupa_masculina,fashion_male_clothing
29,pet_shop,pet_shop
30,moveis_escritorio,office_furniture
31,market_place,market_place
32,eletronicos,electronics
33,eletrodomesticos,home_appliances
34,artigos_de_festas,party_supplies
35,casa_conforto,home_confort
36,construcao_ferramentas_ferramentas,costruction_tools_tools
37,agro_industria_e_comercio,agro_industry_and_commerce
38,moveis_colchao_e_estofado,furniture_mattress_and_upholstery
39,livros_tecnicos,books_technical
40,casa_construcao,home_construction
41,instrumentos_musicais,musical_instruments
42,moveis_sala,furniture_living_room
43,construcao_ferramentas_iluminacao,construction_tools_lights
44,industria_comercio_e_negocios,industry_commerce_and_business
45,alimentos,food
46,artes,art
47,moveis_quarto,furniture_bedroom
48,livros_interesse_geral,books_general_interest
49,construcao_ferramentas_seguranca,construction_tools_safety
50,fashion_underwear_e_moda_praia,fashion_underwear_beach
51,fashion_esporte,fashion_sport
52,sinalizacao_e_seguranca,signaling_and_security
53,pcs,computers
54,artigos_de_natal,christmas_supplies
55,fashion_roupa_feminina,fashio_female_clothing
56,eletrodomesticos_2,home_appliances_2
57,livros_importados,books_imported
58,bebidas,drinks
59,cine_foto,cine_photo
60,la_cuisine,la_cuisine
61,musica,music
62,casa_conforto_2,home_comfort_2
63,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
64,cds_dvds_musicais,cds_dvds_musicals
65,dvds_blu_ray,dvds_blu_ray
66,flores,flowers
67,artes_e_artesanato,arts_and_craftmanship
68,fraldas_higiene,diapers_and_hygiene
69,fashion_roupa_infanto_juvenil,fashion_childrens_clothes
70,seguros_e_servicos,security_and_services
71,portateis_cozinha_e_preparadores_de_alimentos,kitchen_laptops_and_food_preparators
72,pc_gamer,pc_gamer

In [3]:
products2 = products.dropna()
orders2 = orders.dropna()

In [4]:
products3 = pd.merge(products2, translation, on='product_category_name', how='left')
products3['product_category_name'] = products3['product_category_name_english'].combine_first(products3['product_category_name'])

products3 = products3.drop(columns=['product_category_name_english'])
products3.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,baby,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,housewares,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [5]:
prod_impt = products3[['product_id', 'product_category_name']]
prod_impt.shape

(32340, 2)

In [6]:
items2 = pd.merge(items, prod_impt, on='product_id', how='left')
items2.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,furniture_decor
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumery
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,garden_tools

In [7]:
items3 = items2.drop(columns=['order_item_id', 'seller_id', 'shipping_limit_date', 'freight_value'])
items3.head()

,order_id,product_id,price,product_category_name
0,00010242fe8c5a6d1ba2dd792cb16214,4244733e06e7ecb4970a6e2683c13e61,58.90,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,e5f2d52b802189ee658865ca93d83a8f,239.90,pet_shop
2,000229ec398224ef6ca0657da4fc703e,c777355d18b72b67abbeef9df44fd0fd,199.00,furniture_decor
3,00024acbcdf0a6daa1e931b038114c75,7634da152a4610f1595efa32f14722fc,12.99,perfumery
4,00042b26cf59d7ce69dfabb4e55b4fd9,ac6c3623068f30de03045865e4e10089,199.90,garden_tools

In [8]:
order_item = pd.merge(orders2, items3, on='order_id', how='inner')

order_item = order_item.dropna()
order_item.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,product_id,price,product_category_name
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,87285b34884572647811a353c7ac498a,29.99,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,595fac2a385ac33a80bd5114aec74eb8,118.70,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,aa4383b373c6aca5d8797843e5594415,159.90,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,d0b61bfb1de832b15ba9d266ca96e5b0,45.00,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,65266b2da20d04dbe00c5c2d3bb7859e,19.90,stationery

In [9]:
order_item2 = order_item.drop(columns=['order_status', 'order_approved_at', 
                                       'order_delivered_carrier_date','order_delivered_customer_date', 
                                       'order_estimated_delivery_date'])

order_item2.head()

,order_id,customer_id,order_purchase_timestamp,product_id,price,product_category_name
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,87285b34884572647811a353c7ac498a,29.99,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,595fac2a385ac33a80bd5114aec74eb8,118.70,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,aa4383b373c6aca5d8797843e5594415,159.90,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,d0b61bfb1de832b15ba9d266ca96e5b0,45.00,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,65266b2da20d04dbe00c5c2d3bb7859e,19.90,stationery

In [10]:
cust_orders = pd.merge(order_item2, customers, on='customer_id', how='left')

cust_orders2 = cust_orders.drop(columns=['customer_zip_code_prefix', 'customer_city'])

In [11]:
cust_orders2['order_purchase_timestamp'] = pd.to_datetime(cust_orders2['order_purchase_timestamp'])
cust_orders2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108643 entries, 0 to 108642
Data columns (total 8 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  108643 non-null  object
 1   customer_id               108643 non-null  object
 2   order_purchase_timestamp  108643 non-null  datetime64[ns]
 3   product_id                108643 non-null  object
 4   price                     108643 non-null  float64
 5   product_category_name     108643 non-null  object
 6   customer_unique_id        108643 non-null  object
 7   customer_state            108643 non-null  object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 6.6+ MB

In [12]:
cust_reviews = pd.merge(cust_orders2, reviews, on='order_id', how='left')

cust_reviews.head()

,order_id,customer_id,order_purchase_timestamp,product_id,price,product_category_name,customer_unique_id,customer_state,review_id,review_score,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,87285b34884572647811a353c7ac498a,29.99,housewares,7c396fd4830fd04220f754e42b4e5bff,SP,a54f0611adc9ed256b57ede6b6eb5114,4.0,11/10/2017 0:00,12/10/2017 3:43
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,595fac2a385ac33a80bd5114aec74eb8,118.70,perfumery,af07308b275d755c9edb36a90c618231,BA,8d5266042046a06655c8db133d120ba5,4.0,8/8/2018 0:00,8/8/2018 18:37
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,aa4383b373c6aca5d8797843e5594415,159.90,auto,3a653a41f6f9fc3d2a113cf8398680e8,GO,e73b67b67587f7644d5bd1a52deb1b01,5.0,18/8/2018 0:00,22/8/2018 19:07
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,d0b61bfb1de832b15ba9d266ca96e5b0,45.00,pet_shop,7c142cf63193a1473d2e66489a9ae977,RN,359d03e676b3c069f62cadba8dd3f6e8,5.0,3/12/2017 0:00,5/12/2017 19:21
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,65266b2da20d04dbe00c5c2d3bb7859e,19.90,stationery,72632f0f9dd73dfee390c9b22eb56dd6,SP,e50934924e227544ba8246aeb3770dd4,5.0,17/2/2018 0:00,18/2/2018 13:02

In [13]:
cust_reviews2 = cust_reviews.drop(columns=['product_id', 'review_creation_date', 'review_answer_timestamp', 'customer_id'])
cust_reviews2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109278 entries, 0 to 109277
Data columns (total 8 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  109278 non-null  object
 1   order_purchase_timestamp  109278 non-null  datetime64[ns]
 2   price                     109278 non-null  float64
 3   product_category_name     109278 non-null  object
 4   customer_unique_id        109278 non-null  object
 5   customer_state            109278 non-null  object
 6   review_id                 108463 non-null  object
 7   review_score              108463 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 6.7+ MB

In [14]:
cust_reviews3 = cust_reviews2.dropna()

In [15]:
top_1k = cust_reviews3.groupby('customer_unique_id')['order_id'].count().sort_values(ascending=False).head(1000)
top_1k.head()
top_1k_cust = top_1k.index.tolist()

In [16]:
len(top_1k)

1000

In [17]:
# Filter the DataFrame for the top 1000 customers
cust_sample = cust_reviews3[cust_reviews3['customer_unique_id'].isin(top_1k_cust)]

cust_sample.head()

,order_id,order_purchase_timestamp,price,product_category_name,customer_unique_id,customer_state,review_id,review_score
71,68e48e68da1f50f7c5838ea75e3a20dd,2018-06-18 16:02:23,84.9,auto,a464f750556546a0989d9326ec003ccf,SP,0047ca502c37fbba9b3a31eeae3fe0c2,5.0
72,68e48e68da1f50f7c5838ea75e3a20dd,2018-06-18 16:02:23,84.9,auto,a464f750556546a0989d9326ec003ccf,SP,0047ca502c37fbba9b3a31eeae3fe0c2,5.0
73,68e48e68da1f50f7c5838ea75e3a20dd,2018-06-18 16:02:23,84.9,auto,a464f750556546a0989d9326ec003ccf,SP,0047ca502c37fbba9b3a31eeae3fe0c2,5.0
74,68e48e68da1f50f7c5838ea75e3a20dd,2018-06-18 16:02:23,84.9,auto,a464f750556546a0989d9326ec003ccf,SP,0047ca502c37fbba9b3a31eeae3fe0c2,5.0
81,82bce245b1c9148f8d19a55b9ff70644,2017-04-20 17:15:46,38.0,housewares,f9effeed3df9ae063a58c0759b96f8b2,PR,fd793fea4f4a2ddcc956561144b6c04e,1.0

In [18]:
# Apply scaling to review scores
def scale_rating(score):
    if score >= 4:
        return score * 1.5  # Double the weight of positive ratings
    elif score <= 2:
        return score * 0.5  # Reduce the weight of negative ratings
    return score  # Keep neutral ratings as-is

cust_sample['scaled_score'] = cust_sample['review_score'].apply(scale_rating)

cust_sample.head()

C:\Users\jingy\AppData\Local\Temp\ipykernel_9708\1212821042.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_sample['scaled_score'] = cust_sample['review_score'].apply(scale_rating)

,order_id,order_purchase_timestamp,price,product_category_name,customer_unique_id,customer_state,review_id,review_score,scaled_score
71,68e48e68da1f50f7c5838ea75e3a20dd,2018-06-18 16:02:23,84.9,auto,a464f750556546a0989d9326ec003ccf,SP,0047ca502c37fbba9b3a31eeae3fe0c2,5.0,7.5
72,68e48e68da1f50f7c5838ea75e3a20dd,2018-06-18 16:02:23,84.9,auto,a464f750556546a0989d9326ec003ccf,SP,0047ca502c37fbba9b3a31eeae3fe0c2,5.0,7.5
73,68e48e68da1f50f7c5838ea75e3a20dd,2018-06-18 16:02:23,84.9,auto,a464f750556546a0989d9326ec003ccf,SP,0047ca502c37fbba9b3a31eeae3fe0c2,5.0,7.5
74,68e48e68da1f50f7c5838ea75e3a20dd,2018-06-18 16:02:23,84.9,auto,a464f750556546a0989d9326ec003ccf,SP,0047ca502c37fbba9b3a31eeae3fe0c2,5.0,7.5
81,82bce245b1c9148f8d19a55b9ff70644,2017-04-20 17:15:46,38.0,housewares,f9effeed3df9ae063a58c0759b96f8b2,PR,fd793fea4f4a2ddcc956561144b6c04e,1.0,0.5

In [19]:
# Define a function to calculate state similarity dynamically
def calculate_state_similarity(row, target_state):
    return 1 if row['customer_state'] == target_state else 0.5

# Example: Generating recommendations for a specific customer
def compute_state_similarity_for_target_customer(cust_sample, target_customer_id):
    # Get the state of the target customer
    target_state = cust_sample.loc[cust_sample['customer_unique_id'] == target_customer_id, 'customer_state'].values[0]

    # Add a state similarity column, comparing all customers to the target customer
    cust_sample['state_similarity'] = cust_sample['customer_state'].apply(
        lambda state: 1 if state == target_state else 0.5
    )

    return cust_sample

In [20]:
# Step 3: Create the weighted user-item matrix
def create_user_item_matrix(cust_sample, target_customer_id):
    # Update dataset with state similarity
    cust_sample = compute_state_similarity_for_target_customer(cust_sample, target_customer_id)
    
    # Apply weights to review scores based on state similarity
    cust_sample['weighted_score'] = cust_sample['scaled_score'] * cust_sample['state_similarity']

    # Create the user-item matrix
    user_item_matrix = cust_sample.pivot_table(
        index='customer_unique_id',
        columns='product_category_name',
        values='weighted_score',
        aggfunc='mean'
    ).fillna(0)
    
    return user_item_matrix

In [70]:
from sklearn.metrics.pairwise import cosine_similarity

# Step 4: Compute similarity matrix
def compute_similarity_matrix(user_item_matrix):
    customer_similarity = cosine_similarity(user_item_matrix)
    similarity_df = pd.DataFrame(customer_similarity, index=user_item_matrix.index, columns=user_item_matrix.index)
    return similarity_df

# Step 5: Recommend product categories
def recommend_for_customer(customer_id, similarity_df, cust_sample, top_n=5):
    # Find similar customers
    similar_customers = similarity_df[customer_id].sort_values(ascending=False)[1:(2*top_n)].index

    # Get the product categories these customers interacted with
    similar_customer_data = cust_sample[cust_sample['customer_unique_id'].isin(similar_customers)]

    # Get the most popular product categories among these customers
    recommended_categories = similar_customer_data['product_category_name'].value_counts().head(top_n)
    
    return recommended_categories.index.tolist()

# Example usage of the pipeline
# Load and preprocess your dataset: cust_sample

# Define a target customer
target_customer_id = 'f9effeed3df9ae063a58c0759b96f8b2'

# Create the weighted user-item matrix
user_item_matrix = create_user_item_matrix(cust_sample, target_customer_id)

# Compute similarity matrix
similarity_df = compute_similarity_matrix(user_item_matrix)

# Get recommendations for the target customer
recommended_categories = recommend_for_customer(target_customer_id, similarity_df, cust_sample, top_n=5)

print(f"Recommended categories for customer {target_customer_id}: {recommended_categories}")

# a464f750556546a0989d9326ec003ccf
# f7ea4eef770a388bd5b225acfc546604
# f9effeed3df9ae063a58c0759b96f8b2

Recommended categories for customer f9effeed3df9ae063a58c0759b96f8b2: ['housewares']

C:\Users\jingy\AppData\Local\Temp\ipykernel_9708\2207831158.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_sample['state_similarity'] = cust_sample['customer_state'].apply(
C:\Users\jingy\AppData\Local\Temp\ipykernel_9708\647047682.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_sample['weighted_score'] = cust_sample['scaled_score'] * cust_sample['state_similarity']

In [22]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
train_data, test_data = train_test_split(cust_sample, test_size=0.2, random_state=40)

In [23]:
def precision_recall_at_k(model, test_data, k=5):
    hits = 0
    total_relevant = 0
    total_recommended = 0

    # Iterate through each unique customer in the test data
    for customer_id in test_data['customer_unique_id'].unique():
        # Actual items - print actual items to debug
        actual_items = test_data[test_data['customer_unique_id'] == customer_id]['product_category_name'].unique()
        # print(f"Actual items for {type(customer_id)} {customer_id}: {actual_items}")  # Debugging line

        # Predicted items - print predicted items to debug
        try:
            predicted_items = recommend_for_customer(customer_id, similarity_df, cust_sample, top_n=5)  # Your recommendation function
        except:
            predicted_items = []
            # print(predicted_items)

        # Calculate hits and counts
        hits += len(set(predicted_items) & set(actual_items))
        total_recommended += len(predicted_items)
        total_relevant += len(actual_items)
  

    # Calculate precision and recall
    precision = hits / total_recommended if total_recommended > 0 else 0
    recall = hits / total_relevant if total_relevant > 0 else 0

    return precision, recall

# Example usage
precision, recall = precision_recall_at_k(recommend_for_customer, test_data, k=5)
print(f'Accuracy of model in terms of Precision and Recall:') 
print(f"Precision@5: {precision:.2f}")
print(f"Recall@5: {recall:.2f}")

Accuracy of model in terms of Precision and Recall:
Precision@5: 0.60
Recall@5: 0.95